name: rk2
run-name: rk2
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: load_repository
        uses: actions/checkout@v4
      - run: git clone https://github.com/google/googletest third-party/gtest 
      - name: Build
        run: cmake -H. -B build && cmake --build build
      - name: Test
        run: cmake --build build --target test && cmake --build build --target test -- ARGS=--verbose && build/check
      - name: Artefacts
        run: cd build && cpack -G "TGZ"
      - name: Artefacts
        uses: actions/upload-artifact@v4
        with:
          name: example
          path: build/PolicyBasedDesign
